name: base
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python=3.7
  - pip==9.0.3
  - fastai
  - pytorch=1.3.1
  - cudatoolkit=10.0
  - tensorboard>=1.14
  - scikit-learn
  - pip:
    - nvidia-ml-py3
    - transformers==2.1.1
    - youtokentome
    - awscli
